Areas/Admin/Controllers/BlogInfoController.cs
using Blog.Data;
using Blog.Models;
using Blog.Repository.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Web;
using System.Drawing;
using Microsoft.EntityFrameworkCore;
using static System.Net.Mime.MediaTypeNames;

namespace Blog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BlogInfoController : Controller
    {
        private readonly IBlogservice blogservice;
        private readonly ICategoryService categoryService;
        private readonly IWebHostEnvironment _env;
        public BlogInfoController(IBlogservice blogservice,ICategoryService categoryService, IWebHostEnvironment env)
        {
            this.categoryService = categoryService;
            this.blogservice = blogservice; 
            _env = env; 
        }

        public IActionResult BlogList()
        {
            var obj = blogservice.GetBlogs().Result;
            return View(obj);
        }

        public IActionResult Add()
        {
            ViewBag.Category = new SelectList(categoryService.GetCategories().Result, "CategoryId", "CategoryName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Add")]
        public async Task<IActionResult> AddBlog(BlogData obj, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                obj.BlogId = Guid.NewGuid();
                obj.DateCreated = DateTime.UtcNow;
                if (image != null)
                {

                    //Getting the Image upload from server converuing to a url
                    var name = Path.Combine(_env.WebRootPath + "/images",Path.GetFileName(image.FileName));
                     image.CopyTo(new FileStream(name, FileMode.Create));
                    obj.ImageUrl = $"images/{image.FileName}";

                    // Resize(image.FileName);

                }
                _ = await blogservice.AddBlog(obj);

                TempData["AddBlog"] = "Blog saved Successfully";
                return RedirectToAction("BlogList");
            }
            ModelState.AddModelError(string.Empty, "Use correct format");
            return View(obj);
        }

        [ActionName("Delete")]
        public IActionResult Delete(Guid? id)
        {
            if (id != Guid.Empty)
            {
                var checkBlog = blogservice.GetBlogById(id).Result;
                if (checkBlog != null)
                {
                    // first delete the image in the server
                    Action<string> deleteImg = blogservice.DeleteImage;
                    deleteImg(checkBlog.ImageUrl);

                    // then delete the actual blog
                    blogservice.DeleteBlog(checkBlog);

                    TempData["DeleteBlog"] = "Blog deleted Successfully";
                    return RedirectToAction("BlogList");
                }
                TempData["DeleteBlog"] = "Blog cannot be deleted";
                return RedirectToAction("BlogList");

            }
            return NotFound();
        }

        //===== Go to Edit View //
        public IActionResult Edit(Guid? id)
        {
            if (id == Guid.Empty)
            {
                return NotFound();

            }
            var checkBlog = blogservice.GetBlogById(id).Result;
            //var category = await _contect.Category.Where(c => c.CategoryId == id).FirstOrDefaultAsync();
            if (checkBlog != null)
            {
                ViewBag.Category = new SelectList(categoryService.GetCategories().Result, "CategoryId", "CategoryName");
                return View(checkBlog);
            }
            return NotFound();

        }

        // =====  edit the category //
        [ActionName("Edit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBlog(BlogData obj, IFormFile image, List<string> existingTags)
        {
            //============
            // Check if new tags  are not added
            //                            ==============================

            if (obj.Tags == null)
            {
                obj.Tags = new List<string>();
            }

            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    //Getting the Image upload from server converting to a url
                    var name = Path.Combine(_env.WebRootPath + "/images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    obj.ImageUrl = "images/" + image.FileName;

                }
            
                obj.Tags.AddRange(existingTags);
                var date = obj.DateCreated.ToUniversalTime();
                obj.DateCreated = date;
                await blogservice.UpdateBlog(obj);
                TempData["EditBlog"] = "Blog edited successfully";
                return RedirectToAction("BlogList");
            }
            ModelState.AddModelError(string.Empty, "Invalid format");
            return View("Edit",obj);
        }

    }

}

Areas/Admin/Controllers/CategoriesController.cs
using Blog.Data;
using Blog.Models;
using Blog.Repository.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Blog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class CategoriesController : Controller
    {
        //configure services in controller
        private readonly ICategoryService categoryService;
        public CategoriesController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }
        public IActionResult CategoryList()
        {
            var obj = categoryService.GetCategories().Result;
            return View(obj);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Add")]
        public IActionResult AddCategory(Category obj)
        {
            if (ModelState.IsValid)
            {
                _ = categoryService.AddCategory(obj).Result;
                TempData["AddCategory"] = $"{obj.CategoryName} has been added to list Successfully";
                return RedirectToAction("CategoryList");
            }
            ModelState.AddModelError(string.Empty, "Use correct format");
            return View("Add",obj);
        }



        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                var category = categoryService.GetCategoryById(id).Result;
                if (category != null)
                {
                    try
                    {
                        categoryService.DeleteCategory(category);
                    }
                    catch (Microsoft.EntityFrameworkCore.DbUpdateException ex)
                    {
                        TempData["ErrorCategory"] = $"{ex.Message}";
                        return RedirectToAction("CategoryList");
                    }
                    TempData["DeleteCategory"] = $"{category.CategoryName} has been deleted from list Successfully";
                    return RedirectToAction("CategoryList");
                }
                TempData["DeleteCategory"] = "Category cannot be deleted";
                return RedirectToAction("CategoryList");

            }
            return NotFound();
        }

        //===== Go to Edit View //
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();

            }
            var category = categoryService.GetCategoryById(id).Result;   
            if (category != null)
            {
                return View(category);
            }
            return NotFound();

        }

        // =====  edit the category //
        [ActionName("Edit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCategory(Category obj)
        {
                if (ModelState.IsValid)
                {
                       _ = categoryService.UpdateCategory(obj).Result; 
                        TempData["EditCategory"] = $"Category edited successfully as {obj.CategoryName}";
                        return RedirectToAction("CategoryList");
                }
                ModelState.AddModelError(string.Empty, "Invalid format");
                return View(obj);
        }
    }

}

Controllers/BlogContentController.cs
using Microsoft.AspNetCore.Mvc;
using Blog.Data;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
using Blog.Repository.IServices;
using Blog.ViewModels;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Blog.Models;

namespace Blog.Controllers
{
    /// <summary>
    /// delegate that points to all the date converter 
    /// that shows when a blog is posted
    /// </summary>
    /// <param name="date"></param>
    /// <returns> string</returns>
    public delegate string DateCreatedDelegate(Int64 date);
    public class BlogContentController : Controller
    {
        private readonly ILogger<BlogContentController> _logger;
        private readonly IBlogservice blogservice;
        private readonly ICategoryService categoryService;

        public BlogContentController(ILogger<BlogContentController> logger,IBlogservice blogservice, ICategoryService categoryService)
        {
            _logger = logger;
            this.blogservice = blogservice;
            this.categoryService = categoryService;
        }

        public IActionResult data(Guid? id)
        {
            // confirm if the id is empty
            if(id == Guid.Empty)
            {
                return NotFound();
            }
            //check if the id is in the database
            var check = blogservice.GetBlogById(id).Result;
            if(check != null)
            {
                //Find the category Id of the blog since the category name is null in the check variable
                var getCategoryName = categoryService.GetCategoryById(check.CategoryId).Result;
                //show the contents of the category id in the viewbag and get the category name to display in the page
                ViewData["Category"] = $"{getCategoryName.CategoryName}";
                //cull the delegate variable
                DateCreatedDelegate dateDelegate = date;
                ViewData["dateInAgo"] = $"{dateDelegate(check.DateCreated.ToLocalTime().Ticks)}";//calling the date method and adds to the viewbag
                return View(check);
            }
            return NotFound();
        }


        public IActionResult LatestBlog(int? page)
        {
            var latest = blogservice.GetBlogs().Result.Take(3).ToList();

            return PartialView("_LatestBlogsPartial", latest);
        }

        public IActionResult ArchiveBlog()
        {
            var archive = blogservice.GetArchiveBlogs().Result;

            return PartialView("_ArchiveBlogPartial", archive);
        }
        [HttpPost]
        [Authorize]
        public IActionResult AddComment(CommentViewModel comment)
        {
            if (!ModelState.IsValid)
                return View("data",comment.BlogId);
            var result = blogservice.Comment(comment).Result;
            //stops the comment model from showing in the view
            ViewData.ModelState.Clear();
                return View("data",result);
        }

        [Authorize]
        public async Task<IActionResult> LikePost(Guid Id)
        {
            if(Id == Guid.Empty)
            {
                return NotFound();
            }    
             var blog = await blogservice.SaveLike(Id);
            var user = new HttpContextAccessor().HttpContext;

            TempData["LikePost"] = $"Thanks {user.User.Identity.Name},your review is well appreciated";
            return View("data",blog);
        }


        //This method gets the blog's date in ago format 
        public string date(Int64 blogDate)
        {
            const int SECOND = 1;
            const int MINUTE = 60 * SECOND;
            const int HOUR = 60 * MINUTE;
            const int DAY = 24 * HOUR;
            const int MONTH = 30 * DAY;

            var ts = new TimeSpan(DateTime.UtcNow.ToLocalTime().Ticks - blogDate);
            double delta = Math.Abs(ts.TotalSeconds);

            if (delta < 1 * MINUTE)
                return ts.Seconds == 1 ? "one second ago" : ts.Seconds + " seconds ago";

            if (delta < 2 * MINUTE)
                return "a minute ago";

            if (delta < 45 * MINUTE)
                return ts.Minutes + " minutes ago";

            if (delta < 90 * MINUTE)
                return "an hour ago";

            if (delta < 24 * HOUR)
                return ts.Hours + " hours ago";

            if (delta < 48 * HOUR)
                return "yesterday";

            if (delta < 30 * DAY)
                return ts.Days + " days ago";

            if (delta < 12 * MONTH)
            {
                int months = Convert.ToInt32(Math.Floor((double)ts.Days / 30));
                return months <= 1 ? "one month ago" : months + " months ago";
            }
            else
            {
                int years = Convert.ToInt32(Math.Floor((double)ts.Days / 365));
                return years <= 1 ? "one year ago" : years + " years ago";
            }
        }


    }
}

Views/Shared/_ArchiveBlogPartial.cshtml
@using Blog.Models;
@model List<BlogData>

<ul class="list-sidebar">
    @foreach (var item in Model)
    {
        <li>

            <a asp-area="" asp-controller="BlogContent" asp-action="data"
           asp-route-Id="@item.BlogId">@item.Title</a>
        </li>
    }

</ul>

Views/Shared/_BlogFilterPartial.cshtml
@using Blog.Models;
@model List<Category>
<div class="blog-filter">
    <span class="filter-item active-filter" data-filter='all'>All</span>
    @foreach(var item in Model)
    {
    <span class="filter-item" data-filter='@item.CategoryName'>@item.CategoryName</span>
    }
</div>

@section Scripts{
    <script type="text/javascript">
  
          /** Category filter
* */
    $(document).ready(function () {
        $('.filter-item').click(function () {
            const value = $(this).attr('data-filter');
            if (value == 'all') {
                $('.card').show('1000');
            } else {
                $('.card').not('.' + value).hide('1000');
                $('.card').filter('.' + value).show('1000');
            }
        })
    });
  
    </script>
}

Views/Shared/_CommentPartial.cshtml
@using Blog.ViewModels;
@model CommentViewModel
<form class="form-mf" method="post" asp-action="AddComment">
    <div class="row">
        <div class="col-md-12 mb-3">
            <input asp-for="BlogId" readonly hidden>
            <input asp-for="MainCommentId" readonly hidden>
            <div class="form-group">
                <textarea asp-for="Body"  id="textMessage" class="form-control input-mf" placeholder="Comment *" cols="45" rows="8" required></textarea>
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-12">
            <button type="submit" class="button button-a button-big button-rouded">Send Message</button>
        </div>
    </div>
</form>

Views/Shared/_LatestBlogsPartial.cshtml
@using Blog.Models;
@model List<BlogData>

<ul class="list-sidebar">
    @foreach (var item in Model)
    {
         <li>
            <a asp-area="" asp-controller="BlogContent" asp-action="data"
           asp-route-Id="@item.BlogId">@item.Title</a>
        </li>
    }
</ul>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@using Microsoft.AspNetCore.Authentication
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>VaseBlog</title>
  <meta content="Tech blog for software developers, software engineers, etc." name="description">
  <meta content="Html, Css, Javascript, C#, PostgresSql, Asp.Net core, Asp.net Identity" name="keywords">
  <meta name="author" content="PhilsKay" />

  <!-- Favicons -->
  <link href="~/assets/img/icons8-v-67.png" rel="icon">
    <link href="~/assets/img/icons8-v-67.png" rel="icons8-v-67">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" asp-append-version="true">
  <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet" asp-append-version="true">
  <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet" asp-append-version="true">

  <!-- Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet" asp-append-version="true">

    <!--Alertify-->
    <!-- Bootstrap theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />

  <!-- =======================================================
  * Author: PhilsKay
  ======================================================== -->
</head>

<body>
    <!--facebook Share-->
    <div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v14.0&appId=575826043820954&autoLogAppEvents=1" nonce="iCyV6zg4"></script>


  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo fw-bold"><a asp-action="Index" asp-controller="Home">VaseBlog</a></h1>

      <nav id="navbar" class="navbar">
          @if(SignInManager.IsSignedIn(User)){
                    <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                        <button id="logout" type="submit" class="nav-link btn btn-warning btn-sm mx-2 p-1">Logout</button>
                    </form>
          }

        <ul>
            @if(User.Identity.IsAuthenticated && User.IsInRole("Admin")){
                 <li><a class="nav-link scrollto " asp-area="Admin" asp-controller="Home" asp-action="Index">Dashboard</a></li>
            }
         
          <li><a class="nav-link scrollto" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
          <partial name="_LoginPartial" />  
        </ul>

        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

    <div>
            @RenderBody()
    </div>

  
  <!-- ======= Footer ======= -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="copyright-box">
            <p class="copyright">&copy; 2022 <strong>VaseBlog</strong>. All Rights Reserved</p>
            <div class="credits">
              Designed by PhilsKay & Powered by .Net 
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/purecounter/purecounter.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="~/assets/vendor/typed.js/typed.min.js"></script>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/jquery/dist/jquery.js"></script>

    <!-- Alertify JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>

  <!--  Main JS File -->
  <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="" />
    <meta name="author" content="PhilsKay" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] Admin Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/admin/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>


    <!--Alertify-->
    <!-- Bootstrap theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />

</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" asp-area="" asp-action="Index" asp-controller="Home">VaseBlog</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li>
                            <form id="logoutForm" class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <button id="logout" type="submit">Logout</button>
                            </form>
                        </li>
                    }
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Blog & Category</div>

                        <a class="nav-link" asp-area="Admin" asp-controller="Categories" asp-action="CategoryList" >
                            <div class="sb-nav-link-icon"><i class="fas fa-list"></i></div>
                            Category Details
                        </a>
                        <a class="nav-link" asp-area="Admin" asp-controller="Categories" asp-action="Add">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Add Category
                        </a>
                        <a class="nav-link" asp-area="Admin" asp-controller="BlogInfo" asp-action="BlogList">
                            <div class="sb-nav-link-icon"><i class="fas fa-list"></i></div>
                             Blog Details
                        </a>
                        <a class="nav-link" asp-area="Admin" asp-controller="BlogInfo" asp-action="Add">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Add Blog
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    @if (SignInManager.IsSignedIn(User))
                    {
                            <div class="small">Logged in as:</div>
                            <a id="manage" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">@UserManager.GetUserName(User)!</a>

                    }

                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                       <div class="text-muted">&copy; 2022 <strong>VaseBlog</strong>. All Rights Reserved</div>
                        <div>
                            Designed by <a href="#">PhilsKay</a> & Powered by .Net
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

}


    <!-- Alertify JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/admin/js/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="~/admin/js/datatables-simple-demo.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_LayoutIdentity.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Authentication
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Philskay Blog</title>
  <meta content="Tech blog for software developers, software engineers, etc." name="description">
  <meta content="Html, Css, Javascript, C#, PostgresSql, Asp.Net core, Asp.net Identity" name="keywords">
  <meta name="author" content="PhilsKay" />

  <!-- Favicons -->
  <link href="~/assets/img/favicon.png" rel="icon">
  <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">
  <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>


  <!-- =======================================================
  * Author: PhilsKay
  ======================================================== -->
  <style>
      body::before{
          display: block;
          content: "";
          height: 60px;
        }
  </style>
</head>

<body>
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg bg-dark py-3 navbar-dark fixed-top">
        <div class="container">
            <h1 class="logo fw-bold"><a asp-action="Index" asp-controller="Home" asp-area="" class="text-decoration-none text-light">VaseBlog</a></h1>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ms-auto">
                    <li class="mx-2 nav-item">
                        <a class="nav-link text-primary p-1" id="register" asp-area="Identity" asp-page="/Account/Register">Register</a>
                    </li>
                    <li class="mx-2 nav-item">
                        <a class="nav-link text-success p-1" id="login" asp-area="Identity" asp-page="/Account/Login">Login</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="p-5">
                @RenderBody()

        </div>
    </div>

  <!-- Vendor JS Files -->
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

  <!--  Main JS File -->
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

Views/Shared/_SubCommentPartial.cshtml
@using Blog.ViewModels;
@model CommentViewModel
<form method="post" asp-action="AddComment" class="dropdown-menu p-4 w-100">
    <input asp-for="BlogId" readonly hidden>
    <input asp-for="MainCommentId" readonly hidden>
    <div class="form-group">
        <label for="sub-comment" class="form-label">Write a reply</label>
        <textarea asp-for="Body" class="form-control" rows="3" cols="10"></textarea>
        <span asp-validation-for="Body" class="text-danger"></span>
        <br />
        <button type="submit" class="btn btn-outline-warning post-btn">Post</button>
    </div>
</form>